#!/bin/bash
if [ -f '/etc/supervisord.conf' ]; then
  rm /etc/supervisord.conf
fi
cp /etc/cnc_supervisord.conf /etc/supervisord.conf
/bin/echo "[program:dockerized_rails_sample_web]" >> /etc/supervisord.conf
/bin/echo "command=/usr/bin/strikingly/dockerized_rails_sample/start_web" >> /etc/supervisord.conf
/sbin/rsyslogd && /usr/bin/supervisord -c /etc/supervisord.conf
